version: '3'
services:
  movies:
    image: swapnarani99/movies
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: swapnarani99/train
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: swapnarani99/dth
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: swapnarani99/recharge
    ports:
      - "83:80"
    deploy:
      replicas: 3


 
